SELECT
    UID,

    UPPER(TRIM(FINANCIAL_YEAR)) AS FINANCIAL_YEAR,
    UPPER(TRIM(FINANCIAL_QUARTER)) AS FINANCIAL_QUARTER,

    UPPER(TRIM(CONTRACTOR_TAG)) AS CONTRACTOR_TAG,

    UPPER(TRIM(PRACTICE_CODE)) AS PRACTICE_CODE,
    UPPER(REPLACE(TRIM(PRACTICE_POSTCODE), ' ', '')) AS PRACTICE_POSTCODE,

    UPPER(
        CASE 
            WHEN PATIENT_TYPE IN ('Child', 'Non-paying adult', 'Paying adult') 
                THEN PATIENT_TYPE
            ELSE 'Unknown'
        END
    ) AS PATIENT_TYPE,

    UPPER(TRIM(DENTAL_TREATMENT_BAND)) AS DENTAL_TREATMENT_BAND,

    UDA,
    COT

FROM dtable_raw

WHERE 
    PRACTICE_CODE IS NOT NULL
    AND PRACTICE_POSTCODE IS NOT NULL
    AND FINANCIAL_YEAR IS NOT NULL
    AND FINANCIAL_QUARTER IS NOT NULL
    AND UDA IS NOT NULL
    AND COT IS NOT NULL
    AND UDA >= 0
    AND COT >= 0;
